language: cpp
compiler:
 - clang
 - gcc
os:
 - linux
 - osx
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -y libopenal-dev libalut-dev libvorbis-dev libpng-dev libfreetype6-dev
script: mkdir build; cd build; cmake ..; make
